### ISSUE TITLE
'RCore' object has no attribute '_r_core_free'

### ISSUE THREAD

**Issue by Ret2c7** [radareorg/radare2-r2pipe#159]
## Environment

r2pipe language is python

```sh
radare2 5.8.9 31576 @ linux-x86-64
birth: git.5.8.8-1011-g72e00141b3 2024-01-11__11:05:41
commit: 72e00141b32082394592a624ed8567fdb1051b3c
options: gpl -O? cs:5 cl:2 make

Linux x86_64

1.8.4
```

## Description
When I use the r2diaphora plug-in, the following error appears
```bash
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/open_base.py", line 252, in cmd
    res = self._cmd(cmd, **kwargs)
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/open_base.py", line 202, in _cmd_native
    self.native.cmd_str("o " + self.uri)
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/native.py", line 130, in cmd_str
    return self._r_core_cmd_str(self._o, cmd)
AttributeError: 'RCore' object has no attribute '_r_core_cmd_str'
Exception ignored in: <function RCore.__del__ at 0x7f5b75b88ee0>
Traceback (most recent call last):
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/native.py", line 128, in __del__
AttributeError: 'RCore' object has no attribute '_r_core_free'
```
I found that r2lib() in RCORE returned None, which should not be expected. Further follow-up in r2lib() found that the returned lib_name is libr_core.so, and then the following exception will trigger that the file cannot be found. I don’t know if It is the issue of absolute paths and relative paths that causes this problem

![image](https://github.com/radareorg/radare2-r2pipe/assets/59363523/7da5b86c-dbc4-4505-b290-01ed6f8cdf05)

**Comment by trufae** [comment]
Can you hardcode the full path to libr_core? And override what find_library returns and see what happens?

**Comment by Ret2c7** [comment]
I've tried hardcoding lib_name, the value is /usr/local/lib/libr_core.so
![image](https://github.com/radareorg/radare2-r2pipe/assets/59363523/61c3c0e8-a0c8-47bc-80a3-5579faa00f62)
But now a new error appeared
```bash
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/open_base.py", line 252, in cmd
    res = self._cmd(cmd, **kwargs)
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/open_base.py", line 202, in _cmd_native
    self.native.cmd_str("o " + self.uri)
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/native.py", line 130, in cmd_str
    return self._r_core_cmd_str(self._o, cmd)
TypeError: 'tuple' object is not callable
Exception ignored in: <function RCore.__del__ at 0x7f043f994ee0>
Traceback (most recent call last):
  File "/home/c7/.local/lib/python3.10/site-packages/r2pipe/native.py", line 128, in __del__
TypeError: 'tuple' object is not callable
```

**Comment by Ret2c7** [comment]
I tried to make some modifications to the functions in RCore, and the situation is now normal
![image](https://github.com/radareorg/radare2-r2pipe/assets/59363523/c9900483-0701-425d-8974-3e8d1670248b)

**Comment by trufae** [comment]
What do you mean?

**Comment by Ret2c7** [comment]
register() returns a tuple，and received through the following code
```bash
self._r_core_cmd_str = register("r_core_cmd_str", "c_void_p, c_char_p", "c_char_p")
self._r_core_free = register("r_core_free", "c_void_p", "c_void_p")
```
Called through the following code
```bash
def __del__(self):
    self._r_core_free(self._o)
def cmd_str(self, cmd):
    return self._r_core_cmd_str(self._o, cmd)
```
The error message mentions 'tuple' object is not callable
So I changed it to
```bash
def __del__(self):
    self._r_core_free[0](self._o)
def cmd_str(self, cmd):
    return self._r_core_cmd_str[1](self._o, cmd)
```
I don’t know if this modification is in line with expectations

**Comment by trufae** [comment]
ok thats weird, the code works perfectly fine on macOS, but fails on Linux. The good part is that i can reproduce, but your fix breaks macos 🤪 let me do some checks and maybe add tests in the CI and push a proper fix.

Thanks for reporting!

**Comment by trufae** [comment]
Fixed in https://pypi.org/project/r2pipe/1.8.6/

thanks! your patch was actually good, i dont get why mac's python permits to call tupples, its weird
